<?php

namespace PqrsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdjuntoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdjuntoRepository extends EntityRepository
{
}
