<?php

namespace PqrsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogErrorRepository extends EntityRepository
{
}
