<?php

namespace PqrsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VariablesGlobalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariablesGlobalesRepository extends EntityRepository
{
}
