# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

services:
#    pqrs.amazon_s3:
#        class: AmazonS3
#        arguments:
#            options:
#                key: %pqrs.amazon_s3.aws_key%
#                secret: %pqrs.amazon_s3.aws_secret_key%
#    pqrs.file_uploader:
#        class: PqrsBundle\Upload\FileUploader
#        arguments:
#            service: file_storage_filesystem
    pqrs.s3_client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: factory
        arguments:
            -
                key: "AKIAJG4YSV6XQWKRKZKA"
                secret: "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"