<?php

namespace Proxies\__CG__\PqrsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pqrs extends \PqrsBundle\Entity\Pqrs implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'tipo_comunicacion', 'fecha_hora', 'fecha_modificacion', 'fecha_registro', 'pelicula', 'nombre_usuario', 'documento_usuario', 'direccion_correspondencia', 'correo', 'telefono', 'motivo', 'estado', 'respuesta', 'adjuntos_pqrs', 'ciudad', 'multiplex', 'area', 'areas_asignada', 'portal');
        }

        return array('__isInitialized__', 'id', 'tipo_comunicacion', 'fecha_hora', 'fecha_modificacion', 'fecha_registro', 'pelicula', 'nombre_usuario', 'documento_usuario', 'direccion_correspondencia', 'correo', 'telefono', 'motivo', 'estado', 'respuesta', 'adjuntos_pqrs', 'ciudad', 'multiplex', 'area', 'areas_asignada', 'portal');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pqrs $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoComunicacion($tipoComunicacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoComunicacion', array($tipoComunicacion));

        return parent::setTipoComunicacion($tipoComunicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoComunicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoComunicacion', array());

        return parent::getTipoComunicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaHora($fechaHora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaHora', array($fechaHora));

        return parent::setFechaHora($fechaHora);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaHora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaHora', array());

        return parent::getFechaHora();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaModificacion($fechaModificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaModificacion', array($fechaModificacion));

        return parent::setFechaModificacion($fechaModificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaModificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaModificacion', array());

        return parent::getFechaModificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaRegistro($fechaRegistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaRegistro', array($fechaRegistro));

        return parent::setFechaRegistro($fechaRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaRegistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaRegistro', array());

        return parent::getFechaRegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setPelicula($pelicula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPelicula', array($pelicula));

        return parent::setPelicula($pelicula);
    }

    /**
     * {@inheritDoc}
     */
    public function getPelicula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPelicula', array());

        return parent::getPelicula();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreUsuario($nombreUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreUsuario', array($nombreUsuario));

        return parent::setNombreUsuario($nombreUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreUsuario', array());

        return parent::getNombreUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentoUsuario($documentoUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentoUsuario', array($documentoUsuario));

        return parent::setDocumentoUsuario($documentoUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentoUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentoUsuario', array());

        return parent::getDocumentoUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccionCorrespondencia($direccionCorrespondencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccionCorrespondencia', array($direccionCorrespondencia));

        return parent::setDireccionCorrespondencia($direccionCorrespondencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccionCorrespondencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccionCorrespondencia', array());

        return parent::getDireccionCorrespondencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreo($correo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreo', array($correo));

        return parent::setCorreo($correo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreo', array());

        return parent::getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotivo($motivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotivo', array($motivo));

        return parent::setMotivo($motivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotivo', array());

        return parent::getMotivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad($ciudad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', array($ciudad));

        return parent::setCiudad($ciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', array());

        return parent::getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setMultiplex($multiplex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMultiplex', array($multiplex));

        return parent::setMultiplex($multiplex);
    }

    /**
     * {@inheritDoc}
     */
    public function getMultiplex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMultiplex', array());

        return parent::getMultiplex();
    }

    /**
     * {@inheritDoc}
     */
    public function addRespuestum(\PqrsBundle\Entity\Respuesta $respuesta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRespuestum', array($respuesta));

        return parent::addRespuestum($respuesta);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRespuestum(\PqrsBundle\Entity\Respuesta $respuesta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRespuestum', array($respuesta));

        return parent::removeRespuestum($respuesta);
    }

    /**
     * {@inheritDoc}
     */
    public function getRespuesta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRespuesta', array());

        return parent::getRespuesta();
    }

    /**
     * {@inheritDoc}
     */
    public function addAdjuntosPqr(\PqrsBundle\Entity\Adjunto $adjuntosPqrs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdjuntosPqr', array($adjuntosPqrs));

        return parent::addAdjuntosPqr($adjuntosPqrs);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAdjuntosPqr(\PqrsBundle\Entity\Adjunto $adjuntosPqrs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAdjuntosPqr', array($adjuntosPqrs));

        return parent::removeAdjuntosPqr($adjuntosPqrs);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdjuntosPqrs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdjuntosPqrs', array());

        return parent::getAdjuntosPqrs();
    }

    /**
     * {@inheritDoc}
     */
    public function setArea(\PqrsBundle\Entity\Area $area = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArea', array($area));

        return parent::setArea($area);
    }

    /**
     * {@inheritDoc}
     */
    public function getArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArea', array());

        return parent::getArea();
    }

    /**
     * {@inheritDoc}
     */
    public function addAreasAsignada(\PqrsBundle\Entity\AreaPqrs $areasAsignada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAreasAsignada', array($areasAsignada));

        return parent::addAreasAsignada($areasAsignada);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAreasAsignada(\PqrsBundle\Entity\AreaPqrs $areasAsignada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAreasAsignada', array($areasAsignada));

        return parent::removeAreasAsignada($areasAsignada);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreasAsignada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreasAsignada', array());

        return parent::getAreasAsignada();
    }

    /**
     * {@inheritDoc}
     */
    public function setPortal($portal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPortal', array($portal));

        return parent::setPortal($portal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPortal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPortal', array());

        return parent::getPortal();
    }

    /**
     * {@inheritDoc}
     */
    public function setAreaAnt(\PqrsBundle\Entity\Area $areaAnt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAreaAnt', array($areaAnt));

        return parent::setAreaAnt($areaAnt);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreaAnt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreaAnt', array());

        return parent::getAreaAnt();
    }

}
